paascloud:
  oauth2:
    client:
      id: test
      accessTokenUrl: http://172.0.13.37:8000/auth/v1/login
      clientId: admin
      clientSecret: casa
      clientAuthenticationScheme: header

server:
  port: 8989
